// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUscnLjzyzU2lZXLVPzbGWa2HYaAEbX2w',
    appId: '1:106595590421:web:220bcabb72a81cd7c2091c',
    messagingSenderId: '106595590421',
    projectId: 'kafe-1a8f5',
    authDomain: 'kafe-1a8f5.firebaseapp.com',
    storageBucket: 'kafe-1a8f5.firebasestorage.app',
    measurementId: 'G-E01BBYTJD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMpnHXm87h0opCjo6NphsX6bwe1ayl3I',
    appId: '1:106595590421:android:e5a7dd8aca0a24aac2091c',
    messagingSenderId: '106595590421',
    projectId: 'kafe-1a8f5',
    storageBucket: 'kafe-1a8f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YXur9Rbuv9LicxD805tvRAX06mTGZok',
    appId: '1:106595590421:ios:76eb2da3a9ef3406c2091c',
    messagingSenderId: '106595590421',
    projectId: 'kafe-1a8f5',
    storageBucket: 'kafe-1a8f5.firebasestorage.app',
    iosBundleId: 'com.example.kafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5YXur9Rbuv9LicxD805tvRAX06mTGZok',
    appId: '1:106595590421:ios:76eb2da3a9ef3406c2091c',
    messagingSenderId: '106595590421',
    projectId: 'kafe-1a8f5',
    storageBucket: 'kafe-1a8f5.firebasestorage.app',
    iosBundleId: 'com.example.kafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUscnLjzyzU2lZXLVPzbGWa2HYaAEbX2w',
    appId: '1:106595590421:web:08105883c435ce54c2091c',
    messagingSenderId: '106595590421',
    projectId: 'kafe-1a8f5',
    authDomain: 'kafe-1a8f5.firebaseapp.com',
    storageBucket: 'kafe-1a8f5.firebasestorage.app',
    measurementId: 'G-8H73BRXZS7',
  );
}
